package pixelmatch

import (
	"encoding/base64"
	"testing"

	"github.com/raf555/pixelmatch/internal/testutil"
)

func toU8(rgb *[3]int) [3]uint8 {
	return [3]uint8{uint8((*rgb)[0]), uint8((*rgb)[1]), uint8((*rgb)[2])}
}

// TestAgainstJSReference replays cases generated by the JS implementation
// and asserts that this port produces identical diff counts and diff
// buffers, byte for byte.
func TestAgainstJSReference(t *testing.T) {
	cases, err := testutil.GetTestCases()
	if err != nil {
		t.Fatalf("read cases: %s", err.Error())
	}

	if len(cases) == 0 {
		t.Fatal("no cases in cases.json")
	}

	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			img1, err := base64.StdEncoding.DecodeString(c.Img1)
			if err != nil {
				t.Fatal(err)
			}
			img2, err := base64.StdEncoding.DecodeString(c.Img2)
			if err != nil {
				t.Fatal(err)
			}
			wantDiff, err := base64.StdEncoding.DecodeString(c.Diff)
			if err != nil {
				t.Fatal(err)
			}

			opts := DefaultOptions()
			if c.Opts.Threshold != nil {
				opts.Threshold = *c.Opts.Threshold
			}
			if c.Opts.IncludeAA != nil {
				opts.IncludeAA = *c.Opts.IncludeAA
			}
			if c.Opts.Alpha != nil {
				opts.Alpha = *c.Opts.Alpha
			}
			if c.Opts.DiffMask != nil {
				opts.DiffMask = *c.Opts.DiffMask
			}
			if c.Opts.Checkerboard != nil {
				opts.Checkerboard = *c.Opts.Checkerboard
			}
			if c.Opts.DiffColor != nil {
				opts.DiffColor = toU8(c.Opts.DiffColor)
			}
			if c.Opts.AAColor != nil {
				opts.AAColor = toU8(c.Opts.AAColor)
			}
			if c.Opts.DiffColorAlt != nil {
				opts.DiffColorAlt = toU8(c.Opts.DiffColorAlt)
				opts.HasDiffColorAlt = true
			}

			gotOut := make([]byte, len(img1))
			gotN, err := Match(img1, img2, gotOut, c.W, c.H, &opts)
			if err != nil {
				t.Fatal(err)
			}

			if gotN != c.N {
				t.Errorf("diff count mismatch: got %d, want %d (JS)", gotN, c.N)
			}

			if len(gotOut) != len(wantDiff) {
				t.Fatalf("diff buffer length mismatch: got %d, want %d", len(gotOut), len(wantDiff))
			}

			// Compare byte-for-byte. Report the first few mismatches with
			// pixel coordinates to make debugging easier.
			mismatches := 0
			for i := 0; i < len(gotOut); i++ {
				if gotOut[i] != wantDiff[i] {
					if mismatches < 5 {
						pixIdx := i / 4
						x := pixIdx % c.W
						y := pixIdx / c.W
						chans := []string{"R", "G", "B", "A"}
						ch := chans[i%4]
						t.Errorf("diff buffer mismatch at pixel (%d,%d) channel %s: got %d, want %d",
							x, y, ch, gotOut[i], wantDiff[i])
					}
					mismatches++
				}
			}
			if mismatches > 0 {
				t.Errorf("%d of %d bytes differ (%.2f%%)",
					mismatches, len(gotOut),
					100*float64(mismatches)/float64(len(gotOut)))
			}
		})
	}
}
